---
title: "kaplan_meier_analysis"
output:
  pdf_document: default
  html_document: default
---

Import library 
```{r}
library(survival)
library(survminer)
library(tidyverse)
library(readr)
library(dplyr)
library(gtsummary)
library(ggplot2)
```


Import the data 
```{r}
data <- read.csv("~/Documents/Github/bio_stat_projects/data/seer_breat_cancer_dataset.csv", sep = ",")
```

Data Manipulation
```{r}
data$Race <- ifelse(data$Race == "Other (American Indian/AK Native, Asian/Pacific Islander)", "Other", data$Race)
data$Race <- as.factor(data$Race)

data$Marital.Status <- as.factor(data$Marital.Status)

data <- data %>%
  mutate(
    Marital.Status = case_when(
      Marital.Status == "Married (including common law)" ~ "Married", 
      Marital.Status == "Single (never married)" ~ "Single", 
      TRUE ~ Marital.Status # Keep everything else as it
    )
  )

data$T.Stage <- as.factor(data$T.Stage)
data$N.Stage <- as.factor(data$N.Stage)
data$X6th.Stage <- as.factor(data$X6th.Stage)
data$Grade <- as.factor(data$Grade)
data$A.Stage <- as.factor(data$A.Stage)
data$Estrogen.Status <- as.factor(data$Estrogen.Status)
data$Progesterone.Status <- as.factor(data$Progesterone.Status)
data$Status <- ifelse(data$Status == "Dead", 1, 0)

tbl_summary(data)

```




```{r}
library(survival)
library(survminer)

fit <- survfit(Surv(Survival.Months, Status) ~ 1, data = data)

# yes there is an empty plot but that disappears when you knit to pdf

ggsurvplot(
  fit,
  data = data,
  conf.int = TRUE,
  risk.table = TRUE,
  ggtheme = theme_minimal()
)

```


Additional way to plot survival curve
```{r}
ggsurvplot(
  fit, 
  data = data, 
  conf.int = TRUE, 
  risk.table = TRUE, 
  surv.scale = "percent", 
  xlab = "Time (Months)", 
  ylab = "Survival Probability", 
  title = "Kaplan-Meier Survival Curve", 
  palette = "Dark2", 
  censor.shape = 124, 
  censor.size = 4, 
  ggtheme = theme_classic()
)
```






